WebsiteDichVuDiChoThueCDIO4/Models/CHITIETDONHANG.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteDichVuDiChoThueCDIO4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETDONHANG
    {
        public int CTDH_ID { get; set; }
        public Nullable<int> DH_ID { get; set; }
        public Nullable<int> SP_ID { get; set; }
        public string TENSP { get; set; }
        public Nullable<int> SOLUONGSP { get; set; }
        public Nullable<double> DONGIA { get; set; }
        public string HINHANH { get; set; }
    
        public virtual DONHANG DONHANG { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}

WebsiteDichVuDiChoThueCDIO4/Models/DONHANG.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteDichVuDiChoThueCDIO4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONHANG()
        {
            this.CHITIETDONHANGs = new HashSet<CHITIETDONHANG>();
        }
    
        public int DH_ID { get; set; }
        public string DIACHI { get; set; }
        public Nullable<int> SDT { get; set; }
        public Nullable<double> THANHTIEN { get; set; }
        public Nullable<double> PHIGIAOHANG { get; set; }
        public Nullable<int> GH_ID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<int> TK_ID { get; set; }
        public string HOTEN { get; set; }
        public string EMAIL { get; set; }
        public Nullable<bool> DUYET { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONHANG> CHITIETDONHANGs { get; set; }
        public virtual GIAOHANG GIAOHANG { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}

WebsiteDichVuDiChoThueCDIO4/Controllers/DonHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteDichVuDiChoThueCDIO4.Models;
using WebsiteDichVuDiChoThueCDIO4.Conmon;

namespace WebsiteDichVuDiChoThueCDIO4.Controllers
{
    public class DonHangController : Controller
    {
        QLDICHOTHUEEntities2 db = new QLDICHOTHUEEntities2();
        // GET: DonHang
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult HienThiDonHang()
        {
            var session = (UserLogin)Session[WebsiteDichVuDiChoThueCDIO4.Conmon.CommonConstants.USER_SESSION];
            if (session == null)
            {
                return RedirectToAction("DangNhap", "Login");
            }

            var LisDH = db.DONHANGs.Where(n => n.TK_ID == session.UserID);
            return View(LisDH);
        }

        public ActionResult ChiTietDonHang (int DH_ID)
        {
            var session = (UserLogin)Session[WebsiteDichVuDiChoThueCDIO4.Conmon.CommonConstants.USER_SESSION];
            if (session == null)
            {
                return RedirectToAction("DangNhap", "Login");
            }
            var lisCTDH = db.CHITIETDONHANGs.Where(n => n.DH_ID == DH_ID);
            return View(lisCTDH);
        }
        public ActionResult XoaDonHang(int DH_ID)
        {
            
            DONHANG checkSP = db.DONHANGs.SingleOrDefault(n => n.DH_ID == DH_ID);
                
            
            
            if (checkSP != null)
            {
              
                

                // xóa sản phẩm trong giỏ hàng
                db.DONHANGs.Remove(checkSP);
                var listctdh = db.CHITIETDONHANGs.Where(n => n.DH_ID == DH_ID);
                foreach (var item in listctdh)
                {
                    SANPHAM listsp = db.SANPHAMs.SingleOrDefault(n => n.SP_ID == item.SP_ID);
                    listsp.SOLUONGTON = listsp.SOLUONGTON + item.SOLUONGSP;
                    db.SaveChanges();
                }
                db.SaveChanges();
                ViewBag.TBXoaDonHang = "Xóa đơn hàng thành công";
                return RedirectToAction("HienThiDonHang");



            }
            else
            {
                // Nếu không có thì thêm giỏ hàng vào csdl
                Response.StatusCode = 404;
                return null;

            }
        }
    }
}

WebsiteDichVuDiChoThueCDIO4/Views/DonHang/ChiTietDonHang.cshtml
@using WebsiteDichVuDiChoThueCDIO4.Models
@model IEnumerable<CHITIETDONHANG>

@{
    ViewBag.Title = "ChiTietDonHang";
    Layout = "~/Views/Layout/HomeLayout.cshtml";
}

<h2>Chi tiết đơn hàng của tôi</h2>

    <div class="check">

        <div class="col-md-9 cart-items">
            @{int sum = 0; }
            @foreach (var item in Model)
            {
                <div class="cart-header">
                    @*<div class="close1">  </div>*@
                    <div class="cart-sec simpleCart_shelfItem">
                        <div class="cart-item cyc">
                            <img src="@Url.Content("~/Content/images/"+item.HINHANH)" class="img-responsive" alt="">
                        </div>
                        <div class="cart-item-info">
                            <h3><a href="#"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">@item.TENSP</font></font></a><span><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Mẫu số: @item.SP_ID</font></font></span></h3>
                            <ul class="qty">
                                <li><p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Giá sản phẩm: @item.DONGIA</font></font></p></li>
                                <li><p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Số lượng: @item.SOLUONGSP</font></font></p></li>


                            </ul>

                            <div class="delivery">

                                <p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Giá sản phẩm: @((item.DONGIA.GetValueOrDefault(0) * item.SOLUONGSP).Value.ToString("#,##"))</font></font></p>
                                <span><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Được giao sau 2-3 ngày làm việc</font></font></span>
                                <div class="clearfix"></div>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        @{sum = sum + Convert.ToInt32(item.DONGIA.GetValueOrDefault(0) * item.SOLUONGSP);}
                    </div>
                </div>
            }



        </div>

        

WebsiteDichVuDiChoThueCDIO4/Views/DonHang/HienThiDonHang.cshtml
@using WebsiteDichVuDiChoThueCDIO4.Models
@model IEnumerable<DONHANG>


@{
    ViewBag.Title = "HienThiDonHang";
    Layout = "~/Views/Layout/HomeLayout.cshtml";
}
<head>
    <style>
        #customers {
            font-family: Arial, Helvetica, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }

            #customers td, #customers th {
                border: 1px solid #ddd;
                padding: 8px;
            }

            #customers tr:nth-child(even) {
                background-color: #f2f2f2;
            }

            #customers tr:hover {
                background-color: #ddd;
            }

            #customers th {
                padding-top: 12px;
                padding-bottom: 12px;
                text-align: left;
                background-color: #4CAF50;
                color: white;
            }
    </style>
</head>

<h2>Đơn hàng của tôi</h2>


    <div class="a" style="margin-top:20px">
        <table border="1" id="customers">
            <tr>
                <th><label>Mã đơn hàng</label></th>
                <th><label>Họ tên</label></th>
                <th><label>Địa chỉ</label></th>
                <th><label>Số điện thoại</label></th>

                <th><label>Email</label></th>

                <th><label>Thời gian</label></th>
                <th><label>Thành tiền</label></th>
                <th><label>Chức năng xem ct</label></th>
                <th><label>Chức năng hủy</label></th>

            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td><spam>@item.DH_ID</spam></td>
                    <td>@item.HOTEN</td>
                    <td>@item.DIACHI</td>
                    <td>@item.SDT</td>
                    <td>@item.EMAIL</td>
                    <td>@item.DATE</td>
                    <td>@item.THANHTIEN.Value.ToString("#,##")</td>
                    <td><a style="width:50px" href="@Url.Action("ChiTietDonHang","DonHang",new { @DH_ID=item.DH_ID})" class="item_add"><p class="number item_price"><i> </i><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Chi tiết sản phẩm</font></font></p></a></td>
                    @using (Html.BeginForm("XoaDonHang", "DonHang", new { @DH_ID = item.DH_ID }))
                    {
                        <td> <button type="submit" style="width:50px ; background-color:#ec7c24">Hủy</button></td>
                        <spam>@ViewBag.TBXoaDonHang</spam>
                    }


                </tr>
            }
            </table>

    </div>