WebsiteDichVuDiChoThueCDIO4/Models/GIOHANG.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteDichVuDiChoThueCDIO4.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class GIOHANG
    {
        public int GIOHANG_ID { get; set; }
        public string TENSP { get; set; }
        public Nullable<double> GIASP { get; set; }
        public string HINHANH { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<int> TK_ID { get; set; }
        public Nullable<int> SP_ID { get; set; }

        public int thanhtien { get; set; }
        public GIOHANG()
        {

        }
        public GIOHANG(int iSP_ID, int id)
        {
            using (QLDICHOTHUEEntities2 db = new QLDICHOTHUEEntities2())
            {
                this.SP_ID = iSP_ID;
                this.TENSP = db.SANPHAMs.Single(n => n.SP_ID == iSP_ID).TENSP;
                this.GIASP = db.SANPHAMs.Single(n => n.SP_ID == iSP_ID).GIASP;
                this.HINHANH = db.SANPHAMs.Single(n => n.SP_ID == iSP_ID).HINHANH;
                this.SOLUONG = 1;

                this.TK_ID = id;
                this.thanhtien = (int)(GIASP * SOLUONG);
            }
        }

        public GIOHANG(int iSP_ID, int id, int soluong)
        {
            using (QLDICHOTHUEEntities2 db = new QLDICHOTHUEEntities2())
            {
                this.SP_ID = iSP_ID;
                this.TENSP = db.SANPHAMs.Single(n => n.SP_ID == iSP_ID).TENSP;
                this.GIASP = db.SANPHAMs.Single(n => n.SP_ID == iSP_ID).GIASP;
                this.HINHANH = db.SANPHAMs.Single(n => n.SP_ID == iSP_ID).HINHANH;
                this.SOLUONG = soluong;

                this.TK_ID = id;
                this.thanhtien = (int)(this.GIASP * this.SOLUONG);
            }
        }


        public virtual SANPHAM SANPHAM { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}

WebsiteDichVuDiChoThueCDIO4/Controllers/GioHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteDichVuDiChoThueCDIO4.Conmon;
using WebsiteDichVuDiChoThueCDIO4.Models;


namespace WebsiteDichVuDiChoThueCDIO4.Controllers
{
    public class GioHangController : Controller
    {
        QLDICHOTHUEEntities2 db = new QLDICHOTHUEEntities2();

        
        // GET: GioHang
        public ActionResult XemGioHang()
        {
            var session = (UserLogin)Session[WebsiteDichVuDiChoThueCDIO4.Conmon.CommonConstants.USER_SESSION];
            if (session == null)
            {
                return RedirectToAction("DangNhap", "Login");
            }

            
            var listSP = db.GIOHANGs.Where(n => n.TK_ID == session.UserID);



            return View(listSP);
        }

        public ActionResult ThemGioHang(int SP_ID , string iurl)
        {
            var session = (UserLogin)Session[WebsiteDichVuDiChoThueCDIO4.Conmon.CommonConstants.USER_SESSION];
            // kiểm tra đã đăng nhập chưa
            if (session == null)
            {
                return RedirectToAction("DangNhap", "Login");
            }
            // kiểm tra mã sản phẩm xem hợp lệ hay chưa
            SANPHAM listSP = db.SANPHAMs.SingleOrDefault(n => n.SP_ID == SP_ID);
            if(listSP==null)
            {
                // trang đường dẫn không hợp lệ
                Response.StatusCode = 404;
                return null;
            }
            int soluong = 1;
            //trường hợp một sản phẩm đã tồn tại trong giỏ hàng
           GIOHANG checkSP = db.GIOHANGs.SingleOrDefault(n => n.SP_ID == SP_ID && n.TK_ID ==session.UserID );
            if (checkSP != null)
            {
                // kiểm tra số lượng tồn trước khi cho khách hàng thêm sản phẩm
                checkSP.SOLUONG = checkSP.SOLUONG +1;
                db.SaveChanges();
                ViewData["Greeting"] = "true";
                return Redirect(iurl);
            }else
            {
                // Nếu không có thì thêm giỏ hàng vào csdl
                GIOHANG dh = new GIOHANG(SP_ID, session.UserID);
                db.GIOHANGs.Add(dh);
                db.SaveChanges();
                ViewData["Greeting"] = "true";
                return Redirect(iurl);

            }


        }
        
        public ActionResult XoaGioHang(int MaSP)
        {
            // kiểm tra mã sản phẩm xem hợp lệ hay chưa
            SANPHAM listSP = db.SANPHAMs.SingleOrDefault(n => n.SP_ID == MaSP);
            if (listSP == null)
            {
                // trang đường dẫn không hợp lệ
                Response.StatusCode = 404;
                return null;

            }
            var session = (UserLogin)Session[WebsiteDichVuDiChoThueCDIO4.Conmon.CommonConstants.USER_SESSION];
            //trường hợp một sản phẩm đã tồn tại trong giỏ hàng
            GIOHANG checkSP = db.GIOHANGs.SingleOrDefault(n => n.SP_ID == MaSP && n.TK_ID ==session.UserID);
            if (checkSP != null)
            {
                // xóa sản phẩm trong giỏ hàng
                db.GIOHANGs.Remove(checkSP);
                db.SaveChanges();
                return RedirectToAction("XemGioHang");



            }
            else
            {
                // Nếu không có thì thêm giỏ hàng vào csdl
                Response.StatusCode = 404;
                return null;

            }
        }

        public ActionResult SuaGioHang(GIOHANG model, int MaSP)
        {
            // kiểm tra mã sản phẩm xem hợp lệ hay chưa
            SANPHAM listSP = db.SANPHAMs.SingleOrDefault(n => n.SP_ID == MaSP);
            if (listSP == null)
            {
                // trang đường dẫn không hợp lệ
                Response.StatusCode = 404;
                return null;

            }
            var session = (UserLogin)Session[WebsiteDichVuDiChoThueCDIO4.Conmon.CommonConstants.USER_SESSION];

            //trường hợp một sản phẩm đã tồn tại trong giỏ hàng
            GIOHANG checkSP = db.GIOHANGs.SingleOrDefault(n => n.SP_ID == MaSP && n.TK_ID == session.UserID);
            if (checkSP != null)
            {
                // xóa sản phẩm trong giỏ hàng
                checkSP.SOLUONG = model.SOLUONG;
                db.SaveChanges();
                return RedirectToAction("XemGioHang");



            }
            else
            {
                // Nếu không có thì thêm giỏ hàng vào csdl
                Response.StatusCode = 404;
                return null;

            }
        }





        public ActionResult GioHangPartial()
        {
            
            return PartialView();
        }
    }
}

WebsiteDichVuDiChoThueCDIO4/Views/GioHang/GioHangPartial.cshtml
<a href="@Url.Action("XemGioHang","GioHang")"><li><span class="m_1">Giỏ hàng</span><img src="/assets/client/images/bag.png" alt=""></li></a>

WebsiteDichVuDiChoThueCDIO4/Views/GioHang/ThongBao.cshtml
@{
    ViewBag.Title = "ThongBao";
    Layout = "~/Views/Layout/HomeLayout.cshtml";
}

<h2>ThongBao</h2>

WebsiteDichVuDiChoThueCDIO4/Views/GioHang/XemGioHang.cshtml
@using WebsiteDichVuDiChoThueCDIO4.Models
@model IEnumerable<GIOHANG>

@{
    ViewBag.Title = "XemGioHang";
    Layout = "~/Views/Layout/HomeLayout.cshtml";
}


<head>
    <title>Cửa hàng mới Một danh mục thương mại điện tử Mẫu trang web tương ứng Bootstarp phẳng |  Thanh toán :: w3layouts</title>
    <link href="~/Content/css/bootstrap.css" rel="stylesheet" type="text/css" media="all">
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="~/Content/js/jquery.min.js"></script>
    <!-- Custom Theme files -->
    <!--theme-style-->
    <link href="~/Content/css/style.css" rel="stylesheet" type="text/css" media="all">
    <!--//theme-style-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="keywords" content="New Store Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design">
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!--fonts-->
    <link href="http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900" rel="stylesheet" type="text/css"><!--//fonts-->
    <!-- start menu -->
    <link href="~/Content/css/memenu.css" rel="stylesheet" type="text/css" media="all">
    <script type="text/javascript" src="~/Content/js/memenu.js"></script>
    <script>$(document).ready(function () { $(".memenu").memenu(); });</script>
    <script src="~/Content/js/simpleCart.min.js"></script>
    <link type="text/css" rel="stylesheet" charset="UTF-8" href="https://translate.googleapis.com/translate_static/css/translateelement.css">
</head>

<h2>Giỏ hàng của tôi</h2>

<div class="check">

    <div class="col-md-9 cart-items">
         @{int sum=0; }
        @foreach (var item in Model)
        {
            <div class="cart-header" >
                @*<div class="close1">  </div>*@
                <div class="cart-sec simpleCart_shelfItem">
                    <div class="cart-item cyc">
                        <img src="@Url.Content("~/Content/images/"+item.HINHANH)" class="img-responsive" alt="">
                    </div>
                    <div class="cart-item-info">
                        <h3><a href="#"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">@item.TENSP</font></font></a><span><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Mẫu số: @item.SP_ID</font></font></span></h3>
                        <ul class="qty">
                            @using (Html.BeginForm("SuaGioHang", "GioHang", new { @MaSP = item.SP_ID }))
                            {
                                <li><p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Giá sản phẩm: @item.GIASP.Value.ToString("#,##")</font></font></p></li>
                                <li><p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Số lượng:@item.SOLUONG </font></font></p><p>Số lượng sửa</p>@Html.TextBox("SOLUONG") </li>


                                <button type="submit" style="float:right;margin:auto"> Sửa</button>

                            }
                            @using (Html.BeginForm("XoaGioHang", "GioHang", new { @MaSP = item.SP_ID }))
                            {
                                <button type="submit" style="float:right;margin:auto"> Xóa</button>

                            }


                        </ul>

                        <div class="delivery">
                            
                            <p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Phí dịch vụ: @((item.GIASP.GetValueOrDefault(0) * item.SOLUONG).Value.ToString("#,##"))</font></font></p>
                            <span><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Được giao sau 2-3 ngày làm việc</font></font></span>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    @{sum = sum + Convert.ToInt32(item.GIASP.GetValueOrDefault(0) * item.SOLUONG);}
                </div>
            </div>
        }


        
    </div>
    <div class="col-md-3 cart-total">
        <a class="continue" href="/"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Tiếp tục mua hàng</font></font></a>
        <div class="price-details">
            <h3><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Chi tiết giá</font></font></h3>
            <span><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Toàn bộ</font></font></span>
            <span class="total1"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">@sum.ToString("#,##")</font></font></span>
            <span><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Giảm giá</font></font></span>
            <span class="total1"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">---</font></font></span>
            <span><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Phí vận chuyển</font></font></span>
            <span class="total1"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">0</font></font></span>
            <div class="clearfix"></div>
        </div>
        <ul class="total_price">
            <li class="last_price"> <h4><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">TOÀN BỘ</font></font></h4></li>
            <li class="last_price"><span><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">@sum.ToString("#,##")</font></font></span></li>
            <div class="clearfix"> </div>
        </ul>


        <div class="clearfix"></div>
        <a class="order" href="@Url.Action("ThanhToan","ThanhToan")"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Đặt hàng</font></font></a>

    </div>

    <div class="clearfix"> </div>
</div>